# Generated by Django 5.2.12 on 2026-08-05 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='alarm_recipient',
        ),
        migrations.RemoveField(
            model_name='user',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='user',
            name='diagnoses',
        ),
        migrations.RemoveField(
            model_name='user',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='emergency_contact_phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='emergency_contact_phone_2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='emergency_contact_phone_3',
        ),
    ]
