# Generated by Django 5.2.12 on 2026-08-28 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_alarm_recipient_remove_user_allergies_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordhistory',
            options={},
        ),
    ]
