# Generated by Django 5.2.12 on 2026-08-30 11:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointmentcheckin'),
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='follow_up_date',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='notes',
        ),
        migrations.AddField(
            model_name='consultation',
            name='consultation_type',
            field=models.CharField(choices=[('video', 'Video'), ('audio', 'Audio')], default='video', max_length=20),
        ),
        migrations.AddField(
            model_name='consultation',
            name='currency',
            field=models.CharField(default='ETB', max_length=3),
        ),
        migrations.AddField(
            model_name='consultation',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('am', 'Amharic')], default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='consultation',
            name='meeting_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='price',
            field=models.DecimalField(decimal_places=2, default=450, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultation',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('waiting', 'Waiting'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], db_index=True, default='scheduled', max_length=20),
        ),
        migrations.AddField(
            model_name='consultation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='appointments.appointment'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='consultations.consultation'),
        ),
    ]
