# Generated by Django 5.2.12 on 2026-08-29 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_emergencycontact_alter_medicaldocument_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_families', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FamilyInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation_type', models.CharField(choices=[('member', 'Family Member'), ('patient_claim', 'Patient Account Claim')], max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('role', models.CharField(blank=True, choices=[('owner', 'Owner'), ('member', 'Member'), ('caregiver', 'Caregiver')], max_length=20)),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('otp_hash', models.CharField(blank=True, default='', max_length=64)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('otp_attempts', models.PositiveIntegerField(default=0)),
                ('contact_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_family_invitations', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='families.family')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='family_invitations_sent', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claim_invitations', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('member', 'Member'), ('caregiver', 'Caregiver')], default='member', max_length=20)),
                ('can_view_patient_records', models.BooleanField(default=False)),
                ('can_manage_appointments', models.BooleanField(default=False)),
                ('can_manage_medications', models.BooleanField(default=False)),
                ('can_manage_family_members', models.BooleanField(default=False)),
                ('can_manage_family_patients', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='families.family')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='family_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('self', 'Self'), ('spouse', 'Spouse'), ('parent', 'Parent'), ('child', 'Child'), ('sibling', 'Sibling'), ('relative', 'Relative'), ('other', 'Other')], default='other', max_length=30)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='families.family')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='family_relationships', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='InvitationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=10)),
                ('destination', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='families.familyinvitation')),
            ],
        ),
        migrations.AddIndex(
            model_name='family',
            index=models.Index(fields=['created_by'], name='families_fa_created_6a73a9_idx'),
        ),
        migrations.AddIndex(
            model_name='familyinvitation',
            index=models.Index(fields=['family', 'status'], name='families_fa_family__5d0556_idx'),
        ),
        migrations.AddIndex(
            model_name='familyinvitation',
            index=models.Index(fields=['status', 'expires_at'], name='families_fa_status_a43084_idx'),
        ),
        migrations.AddIndex(
            model_name='familyinvitation',
            index=models.Index(fields=['email', 'status'], name='families_fa_email_7ad01f_idx'),
        ),
        migrations.AddIndex(
            model_name='familyinvitation',
            index=models.Index(fields=['phone_number', 'status'], name='families_fa_phone_n_5da5e3_idx'),
        ),
        migrations.AddIndex(
            model_name='familymember',
            index=models.Index(fields=['family', 'role'], name='families_fa_family__e485f4_idx'),
        ),
        migrations.AddIndex(
            model_name='familymember',
            index=models.Index(fields=['user', 'family'], name='families_fa_user_id_3190e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='familymember',
            constraint=models.UniqueConstraint(fields=('family', 'user'), name='unique_family_member'),
        ),
        migrations.AddConstraint(
            model_name='familymember',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'owner')), fields=('family',), name='unique_family_owner'),
        ),
        migrations.AddIndex(
            model_name='familypatient',
            index=models.Index(fields=['family', 'patient'], name='families_fa_family__e6bd8a_idx'),
        ),
        migrations.AddIndex(
            model_name='familypatient',
            index=models.Index(fields=['patient', 'family'], name='families_fa_patient_b77c2d_idx'),
        ),
        migrations.AddConstraint(
            model_name='familypatient',
            constraint=models.UniqueConstraint(fields=('family', 'patient'), name='unique_family_patient'),
        ),
        migrations.AddConstraint(
            model_name='familypatient',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('family',), name='unique_primary_family_patient'),
        ),
    ]
