# Generated by Django 5.2.12 on 2026-08-29 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0001_initial'),
        ('patients', '0002_emergencycontact_alter_medicaldocument_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='familyinvitation',
            name='otp_locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='familyinvitation',
            name='otp_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FamilyAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('family_created', 'Family Created'), ('patient_created', 'Patient Created'), ('member_invited', 'Family Member Invited'), ('patient_claim_invited', 'Patient Claim Invited'), ('invitation_otp_requested', 'Invitation OTP Requested'), ('invitation_contact_verified', 'Invitation Contact Verified'), ('member_accepted', 'Family Membership Accepted'), ('member_registered', 'Family Member Registered'), ('patient_claimed', 'Patient Account Claimed'), ('invitation_cancelled', 'Invitation Cancelled'), ('invitation_expired', 'Invitation Expired'), ('otp_locked', 'OTP Verification Locked')], max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='families.family')),
                ('invitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='families.familyinvitation')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_audit_logs', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['family', '-created_at'], name='fa_family_created_idx'), models.Index(fields=['actor', '-created_at'], name='fa_actor_created_idx'), models.Index(fields=['action', '-created_at'], name='fa_action_created_idx'), models.Index(fields=['invitation', '-created_at'], name='fa_inv_created_idx'), models.Index(fields=['patient', '-created_at'], name='fa_patient_created_idx')],
            },
        ),
    ]
