import { Patient } from "@/models/Patient";

export interface AppointmentCheckIn {
    checked_in_at: string,
    latitude: string,
    longitude: string,
    gps_verified: string,
    created_at: string,
}

export interface Appointment {
    id: number,
    patient: Patient,
    patient_name: string,
    doctor: string,
    doctor_name: string,
    doctor_specialty: string,
    appointment_date: string,
    appointment_time: string,
    end_time: string,
    duration_minutes: string,
    status: string,
    status_display: string,
    reason_for_visit: string,
    confirmed_at: string,
    completed_at: string,
    cancelled_at: string,
    cancelled_by: string,
    cancelled_by_name: string,
    cancellation_reason: string,
    check_in: AppointmentCheckIn,
    is_upcoming: boolean,
    can_cancel: boolean,
    can_confirm: boolean,
    can_complete: boolean,
    can_mark_no_show: boolean,
    created_at: boolean,
    updated_at: boolean,
}

export interface Consultaions {
    id: number,
    appointment: Appointment,
    patient_name: string,
    doctor_name: string, 
    specialty_name: string,
    appointment_date: string, 
    appointment_time: string, 
    duration_minutes: string, 
    appointment_status: string,
    consultation_type: string, 
    language: string, 
    status: string, 
    price: string, 
    currency: string,
    meeting_url: string, 
    started_at: string, 
    ended_at: string, 
    created_at: string, 
    updated_at: string,
}