# Generated by Django 5.2.12 on 2026-09-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_online',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
